GET http://localhost:5237/reviews/4

###
POST http://localhost:5237/reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNSIsIkVtYWlsIjoiZUBhYmMuY29tIiwibmJmIjoxNzMyMTk0MDU1LCJleHAiOjE3MzIxOTc2NTUsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.xv3WzBTVNEFb2Kb8ilg7z-0A40gbH_zWe1bEET8PfEk
Content-Type: application/json

{
    "carId": 4,
    "comment": "abc",
    "rating": 5
}

###
GET http://localhost:5237/reviews/average-rating/4